#!/bin/zsh

local changelog="\n\n[Changelog] Please update CHANGELOG before commit.\n\n"

do_exit() {
  echo -e "$1"
  exit 1
}

# block if changelog has not been updated
if [[ ! $(git diff --name-only origin/main | grep --quiet "CHANGELOG") ]]; then
  do_exit $changelog
  exit 1
fi

unset do_exit

exit 0
