* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
***_ list-item1
****_ list-item1.1
****_ list-item1.2
*****_ list-item1.2.1
*****_ list-item1.2.2
****_ list-item1.3
***_ list-item2
***_ list-item3
** NewLinux
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio