@startmindmap

* A
**_ B
***_ C
***_ D
***_ E
***_ F
***_ G
***_ H
****_ I bug here for legacy cybermonday implementation
****_ J here also
**_ K
***_ L
****_ M
*****_ N
*****_ O
*****_ P
*****_ Q
*****_ R
****_ S
***_ T
***_ U
****_ V here also
****_ W here also
****_ X here also
****_ Y here also
@endmindmap
