name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  XDG_CONFIG_HOME: $HOME/.config

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Prepare java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          # (optional) To avoid rate limit errors please provide github token
          # github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out practicalli clojure-cli-config
        uses: actions/checkout@master
        with:
          repository: practicalli/clojure-cli-config
          path: practicalli

      - name: Use practicalli
        run: mkdir -p $XDG_CONFIG_HOME/clojure && cp practicalli/deps.edn $XDG_CONFIG_HOME/clojure/deps.edn

      - name: Execute tests on Linux and MacOS
        run: clojure -T:build obarbeau.build/test
